name: Build

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  unit-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]

    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@master
      - name: Testing
        run: |
          make build
          go test ./pkg/...
